language: java
jdk:
- oraclejdk7
script: bash build.sh
env:
  global:
    secure: bWxNgj5f/2vCTHUNsdan5wHB0sqJnWZahMyHJM/fBWY3OW3r4qWVYeGuwS1O89/xR5agXcqHuefSG2l5AtBbvjObK+GJzZQpNClmNjnHLgWQ9WjwitlLq35phlN4K8y19EnS0TgY6aALvN7howxbydqU/FGeXkZjOzy9r9PvaVE=
