language: java
jdk:
- oraclejdk7
script: bash test2.sh
env:
  global:
  - secure: kOUm17yuE1ioBiLI8aFlMATI2RSKXoqKI7nY1+57XKvqb0lg9zYrRVFAIAOoT4lC3YHgrkrnjB4Nfpdh6FgKtGQj1NLed6JHatd4tdJMfjfS51LUoSvM+o6FLISWKAlWishpRWrIsBa2pZjsKxrwwp9Hn/4xlqJsJ88aai/zJtI=
